package com.nextdocs.ai.enumeraciones;

public enum AccionAuditoria {

	DOCUMENTO_INGRESADO,
	DOCUMENTO_DESCARGADO,
	DOCUMENTO_CONSULTADO,
	DOCUMENTO_SEGMENTADO,
	DOCUMENTO_REPROCESADO,
	DOCUMENTO_ELIMINADO,
	EXTRACCION_EJECUTADA,
	VALIDACION_EJECUTADA,
	REVISION_REGISTRADA,
	CAMPO_CORREGIDO,
	DECISION_SOBREESCRITA,
	EXCEPCION_ASIGNADA,
	EXCEPCION_RESUELTA,
	PLANTILLA_CREADA,
	PLANTILLA_VERSIONADA,
	PLANTILLA_PUBLICADA,
	PLANTILLA_DEPRECADA,
	PLANTILLA_REVERTIDA,
	USUARIO_AUTENTICADO,
	USUARIO_CREADO,
	USUARIO_MODIFICADO,
	CUENTA_SERVICIO_CREADA,
	CUENTA_SERVICIO_REVOCADA,
	ACCESO_DENEGADO,
	POLITICA_MODIFICADA,
	RETENCION_APLICADA,
	WEBHOOK_ENTREGADO,
	PROVEEDOR_CONFIGURADO;

	public static AccionAuditoria desde(String valor) {
		if (valor == null) {
			return null;
		}
		for (AccionAuditoria elemento : values()) {
			if (elemento.name().equalsIgnoreCase(valor.trim())) {
				return elemento;
			}
		}
		return null;
	}
}
