package com.nextdocs.ai.enumeraciones;

public enum AccionAuditoria {

	DOCUMENTO_INGRESADO,
	DOCUMENTO_DESCARGADO,
	DOCUMENTO_CONSULTADO,
	DOCUMENTO_SEGMENTADO,
	DOCUMENTO_REPROCESADO,
	DOCUMENTO_ELIMINADO,
	EXTRACCION_EJECUTADA,
	VALIDACION_EJECUTADA,
	REVISION_REGISTRADA,
	CAMPO_CORREGIDO,
	DECISION_SOBREESCRITA,
	EXCEPCION_ASIGNADA,
	EXCEPCION_RESUELTA,
	PLANTILLA_CREADA,
	PLANTILLA_VERSIONADA,
	PLANTILLA_PUBLICADA,
	PLANTILLA_DEPRECADA,
	PLANTILLA_REVERTIDA,
	USUARIO_AUTENTICADO,
	USUARIO_CREADO,
	USUARIO_MODIFICADO,
	USUARIO_BLOQUEADO,
	USUARIO_DESBLOQUEADO,
	USUARIO_ELIMINADO,
	CLAVE_MODIFICADA,
	CLAVE_RESTABLECIDA,
	ROL_CREADO,
	ROL_MODIFICADO,
	ROL_ELIMINADO,
	TENANT_CREADO,
	TENANT_MODIFICADO,
	CUENTA_SERVICIO_CREADA,
	CUENTA_SERVICIO_REVOCADA,
	ACCESO_DENEGADO,
	POLITICA_MODIFICADA,
	RETENCION_APLICADA,
	RETENCION_CICLO_EJECUTADO,
	RETENCION_LEGAL_MODIFICADA,
	AUDITORIA_EXPORTADA,
	AUDITORIA_CONSULTADA,
	WEBHOOK_ENTREGADO,
	WEBHOOK_SUSCRITO,
	WEBHOOK_MODIFICADO,
	WEBHOOK_PAUSADO,
	WEBHOOK_REACTIVADO,
	WEBHOOK_ELIMINADO,
	WEBHOOK_PROBADO,
	WEBHOOK_REINTENTADO,
	PROVEEDOR_CONFIGURADO;

	public static AccionAuditoria desde(String valor) {
		if (valor == null) {
			return null;
		}
		for (AccionAuditoria elemento : values()) {
			if (elemento.name().equalsIgnoreCase(valor.trim())) {
				return elemento;
			}
		}
		return null;
	}
}
